apiVersion: v1
kind: Service
metadata:
  name: swe645-credit-service
spec:
  type: LoadBalancer
  selector:
    app: swe645-credit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
